name: notify-release
on:
  workflow_dispatch:
  schedule:
    - cron: '30 16 * * *'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Notify release
        uses: nearform/github-action-notify-release@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          stale-days: 0